"""Render a map panel for each charging plan passed on the command line.

Each panel draws the district road network with the deployed stations in red,
sized by installed capacity. Panels are written as separate images so the paper
can compose them with subfloat and get proper (a), (b), ... labels.

Plans are taken only from the arguments -- nothing is auto-detected. compare_rl.py
overwrites Results/optimal_plan/<district>/plan_*.pkl on every run, so the files
sitting there do not necessarily belong to the run whose numbers are in the paper;
naming them explicitly is what keeps the figure and the table describing the same
plans. The station count printed for each panel is there to be checked against the
table before the figure is used.

Usage:
    python src/analysis/plot_plan_maps.py --location DongDa \
        "Existing infrastructure=custom_environment/data/Graph/DongDa/new_existingplan_DongDa.pkl" \
        "Greedy-Benefit=Results/optimal_plan/DongDa/plan_G_Benefit.pkl" \
        "Grid-aware DQN=Results/optimal_plan/DongDa/plan_RL_144102.pkl"

A bare path is accepted too; its label is then derived from the file name.
"""
import os
import sys
import pickle
import argparse

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import osmnx as ox

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
if project_root not in sys.path:
    sys.path.append(project_root)

import custom_environment.helpers as H

STATION_COLOR = "#d62728"
JUNCTION_COLOR = "#b0b0b0"
EDGE_COLOR = "#9a9a9a"


def capability_mw(station):
    """Installed capacity in MW.

    The raw new_existingplan_*.pkl files have never been through s_dictionnary, so
    they carry no "capability" key; without this fallback the baseline panel would
    draw every existing station at the smallest marker and look incomparable to the
    others. Same formula as helpers.charging_capability.
    """
    cap = station[2].get("capability") if len(station) > 2 and isinstance(station[2], dict) else None
    if cap is None:
        cap = float(np.sum(H.CHARGING_POWER * np.asarray(station[1]))) / 1000.0
    return cap


def station_sizes(graph, plan):
    """Plain junctions stay small; stations scale with installed capacity (MW)."""
    by_node = {s[0][0]: s for s in plan}
    sizes = []
    for node in graph.nodes():
        s = by_node.get(node)
        if s is None:
            sizes.append(1.5)
            continue
        cap = capability_mw(s)
        sizes.append(9 if cap < 0.25 else 16 if cap < 0.75 else 25 if cap < 1.5 else 38)
    return sizes


def draw_panel(graph, plan, out_path, legend=False, dpi=300):
    station_ids = {s[0][0] for s in plan}
    node_colors = [STATION_COLOR if n in station_ids else JUNCTION_COLOR for n in graph.nodes()]

    fig, ax = ox.plot_graph(
        graph,
        bgcolor="white",
        node_color=node_colors,
        node_size=station_sizes(graph, plan),
        node_zorder=3,
        edge_color=EDGE_COLOR,
        edge_linewidth=0.25,
        edge_alpha=0.9,
        show=False,
        close=False,
        save=False,
    )
    if legend:
        handles = [
            Line2D([0], [0], marker="o", color="w", markerfacecolor=STATION_COLOR,
                   markersize=6, label="Charging station"),
            Line2D([0], [0], marker="o", color="w", markerfacecolor=JUNCTION_COLOR,
                   markersize=3, label="Road junction"),
        ]
        ax.legend(handles=handles, loc="lower left", frameon=True, framealpha=0.9,
                  fontsize=7, borderpad=0.4)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight", pad_inches=0.01, facecolor="white")
    plt.close(fig)


def build_latex(panels, location, width, per_row, graphics_prefix):
    """The figure* block, as a string, ready to be \\input from the paper."""
    lines = ["% Generated by src/analysis/plot_plan_maps.py -- do not edit by hand.",
             "\\begin{figure*}[t]", "\\centering"]
    for i, (label, path) in enumerate(panels):
        rel = os.path.relpath(path, project_root).replace("\\", "/")
        if graphics_prefix:
            rel = graphics_prefix.rstrip("/") + "/" + os.path.basename(rel)
        last = (i + 1 == len(panels))
        sep = "" if last else ("\\\\" if (i + 1) % per_row == 0 else "\\hfill")
        lines.append("\\subfloat[%s]{\\includegraphics[width=%.2f\\textwidth]{%s}}%s"
                     % (label, width, rel, sep))
    lines += ["\\caption{Charging station placement on %s. Marker size scales with "
              "the installed capacity of the station.}" % location,
              "\\label{fig:maps_%s}" % location.lower(),
              "\\end{figure*}", ""]
    return "\n".join(lines)


def parse_entry(entry):
    """'Label=path' or bare 'path'; returns (label, absolute path, output stem)."""
    label, _, path = entry.partition("=")
    if not path:
        path, label = label, ""
    abs_path = path if os.path.isabs(path) else os.path.join(project_root, path)
    stem = os.path.splitext(os.path.basename(abs_path))[0]
    if stem.startswith("plan_"):
        stem = stem[len("plan_"):]
    return (label or stem.replace("_", " ")), abs_path, stem


def main():
    p = argparse.ArgumentParser(
        description="Render one map panel per charging plan given on the command line.")
    p.add_argument("plans", nargs="+", metavar="[LABEL=]PLAN.pkl",
                   help="Plan pickles to render, in figure order")
    p.add_argument("--location", required=True, help="District, used to load the road graph")
    p.add_argument("--out_dir", default=None, help="Default: Results/figures/<location>")
    p.add_argument("--dpi", type=int, default=300)
    p.add_argument("--legend", choices=["none", "first", "all"], default="first")
    p.add_argument("--width", type=float, default=0.32,
                   help="subfloat width as a fraction of \\textwidth in the emitted LaTeX")
    p.add_argument("--per_row", type=int, default=3, help="panels per row in the emitted LaTeX")
    p.add_argument("--tex_out", default=None,
                   help="Where to write the figure block; default <out_dir>/fig_maps_<location>.tex")
    p.add_argument("--graphics_prefix", default=None,
                   help="Rewrite image paths to this prefix, for when the .tex is compiled "
                        "from a different directory than the repository root")
    args = p.parse_args()

    graph_file = os.path.join(project_root, "custom_environment", "data", "Graph",
                              args.location, f"{args.location}.graphml")
    if not os.path.exists(graph_file):
        sys.exit(f"Road graph not found: {graph_file}")
    graph = ox.load_graphml(graph_file)
    out_dir = args.out_dir or os.path.join(project_root, "Results", "figures", args.location)

    written = []
    for entry in args.plans:
        label, path, stem = parse_entry(entry)
        if not os.path.exists(path):
            sys.exit(f"Plan not found: {path}")
        with open(path, "rb") as f:
            plan = pickle.load(f)
        out_path = os.path.join(out_dir, f"map_{args.location}_{stem}.png")
        draw_panel(graph, plan, out_path,
                   legend=(args.legend == "all" or (args.legend == "first" and not written)),
                   dpi=args.dpi)
        cap = sum(capability_mw(s) for s in plan)
        print("  %-26s %3d stations, %6.2f MW  ->  %s"
              % (label, len(plan), cap, os.path.basename(out_path)))
        written.append((label, out_path))

    print("\nCheck those station counts against the results table before using the figure.")

    if len(written) > 1:
        cols = min(args.per_row, len(written))
        rows = (len(written) + cols - 1) // cols
        fig, axes = plt.subplots(rows, cols, figsize=(4.2 * cols, 4.2 * rows), squeeze=False)
        flat = list(axes.flat)
        for ax, (label, path) in zip(flat, written):
            ax.imshow(plt.imread(path))
            ax.set_title(label, fontsize=9)
            ax.axis("off")
        for ax in flat[len(written):]:
            ax.axis("off")
        sheet = os.path.join(out_dir, f"contact_sheet_{args.location}.png")
        fig.tight_layout()
        fig.savefig(sheet, dpi=110, facecolor="white")
        plt.close(fig)
        print(f"Contact sheet: {sheet}")

    tex = build_latex(written, args.location, args.width, args.per_row, args.graphics_prefix)
    tex_path = args.tex_out or os.path.join(out_dir, f"fig_maps_{args.location}.tex")
    os.makedirs(os.path.dirname(tex_path), exist_ok=True)
    with open(tex_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(tex)
    print("\nLaTeX written to %s" % os.path.relpath(tex_path, project_root))
    print("Include it with:  \\input{%s}\n"
          % os.path.relpath(tex_path, project_root).replace("\\", "/"))
    print(tex)


if __name__ == "__main__":
    main()
